### ISSUE TITLE
Pre-Built Toolset

### ISSUE THREAD

**Issue by thielj** [shkolnick-kun/stvd-sdcc#3]
Do you have a pre-built toolset and setup instructions somewhere?

**Comment by shkolnick-kun** [comment]
Hi, @thielj !

No, I have no pre-built binaries.
This is experimental project, and at the moment the toolset may only build a project in STVD.
Debugging with sdcc is not supported by ST-s version of gdb (see #2).

I don't see the point spend more time on this project, because we can build stm8 projects with e.g. Code::Blocks and we don't need any "compatibility layer" in such case.

Cheers.

**Comment by thielj** [comment]
Thanks for the quick reply - may I suggest to update the README with the current status.

**Comment by shkolnick-kun** [comment]
OK
